openapi: 3.0.3
info:
  title: Gateway API
  version: latest
paths:
  /versions:
    get:
      summary: Show stack version information
      operationId: getVersions
      security:
        - NoAuthorization: []
        - Authorization: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetVersionsResponse'

components:
  schemas:
    Version:
      type: object
      properties:
        name:
          type: string
          description: Name of the component
        version:
          type: string
          description: Version of the component currently deployed
        health:
          type: boolean
          description: Whether the component is reporting itself healthy
      required:
        - name
        - version
        - health
    GetVersionsResponse:
      type: object
      properties:
        region:
          type: string
          description: Region the stack is deployed in
        env:
          type: string
          description: Environment the stack is deployed in
        versions:
          type: array
          description: Version and health of each component in the stack
          items:
            $ref: '#/components/schemas/Version'
      required:
        - region
        - env
        - versions